// Shared list of permission keys. Mirrors the seeded `permissions` table.
// Frontend uses this for static permission gating; server is the source of truth.

const PERMISSIONS = {
  invoice: {
    view: 'invoice.view',
    create: 'invoice.create',
    editRequest: 'invoice.edit_request',
    editApprove: 'invoice.edit_approve',
    editDirect: 'invoice.edit_direct',
    cancel: 'invoice.cancel',
    refund: 'invoice.refund',
    print: 'invoice.print',
    download: 'invoice.download',
  },
  product: {
    view: 'product.view',
    create: 'product.create',
    edit: 'product.edit',
    delete: 'product.delete',
    adjustStock: 'product.adjust_stock',
    viewCost: 'product.view_cost',
  },
  supplier: {
    view: 'supplier.view',
    create: 'supplier.create',
    edit: 'supplier.edit',
    delete: 'supplier.delete',
    poCreate: 'supplier.purchase_order.create',
    poPay: 'supplier.purchase_order.pay',
  },
  customer: {
    view: 'customer.view',
    create: 'customer.create',
    edit: 'customer.edit',
    delete: 'customer.delete',
    collectPayment: 'customer.collect_payment',
    viewBalance: 'customer.view_balance',
  },
  employee: {
    view: 'employee.view',
    create: 'employee.create',
    edit: 'employee.edit',
    delete: 'employee.delete',
  },
  user: {
    create: 'user.create',
    edit: 'user.edit',
    changeRole: 'user.change_role',
    forceLogout: 'user.force_logout',
  },
  stock: {
    view: 'stock.view',
    adjustRequest: 'stock.adjust_request',
    adjustApprove: 'stock.adjust_approve',
    adjustDirect: 'stock.adjust_direct',
    countInitiate: 'stock.count_initiate',
    countApprove: 'stock.count_approve',
  },
  cash: { view: 'cash.view', adjust: 'cash.adjust' },
  bank: { view: 'bank.view', transact: 'bank.transact' },
  ret: {
    request: 'return.request',
    approve: 'return.approve',
    process: 'return.process',
  },
  attendance: {
    viewOwn: 'attendance.view_own',
    viewAll: 'attendance.view_all',
    markManual: 'attendance.mark_manual',
    correctionRequest: 'attendance.correction_request',
    correctionApprove: 'attendance.correction_approve',
  },
  bills: { view: 'bills.view', pay: 'bills.pay', manage: 'bills.manage' },
  finance: {
    dashboard: 'finance.view_dashboard',
    pl: 'finance.view_pl',
    balanceSheet: 'finance.view_balance_sheet',
    cashflow: 'finance.view_cashflow',
    vat: 'finance.view_vat',
    journal: 'finance.view_journal',
    closePeriod: 'finance.close_period',
    exportReports: 'finance.export_reports',
  },
  report: {
    sales: 'report.sales',
    inventory: 'report.inventory',
    suppliers: 'report.suppliers',
    customers: 'report.customers',
    employees: 'report.employees',
    attendance: 'report.attendance',
    warranty: 'report.warranty',
    returns: 'report.returns',
    bills: 'report.bills',
    analytics: 'report.analytics',
    exportPdf: 'report.export_pdf',
    exportCsv: 'report.export_csv',
    exportExcel: 'report.export_excel',
    perfOwn: 'report.employee_performance_own',
    perfAll: 'report.employee_performance_all',
  },
  analytics: {
    peaks: 'analytics.view_peaks',
    reorder: 'analytics.view_reorder',
    exportForecast: 'analytics.export_forecast',
  },
  backup: {
    view: 'backup.view',
    runManual: 'backup.run_manual',
    restore: 'backup.restore',
    configure: 'backup.configure',
  },
  settings: { view: 'settings.view', edit: 'settings.edit' },
  errors: { viewAll: 'errors.view_all', resolve: 'errors.resolve' },
  bug: { viewAll: 'bug.view_all', manage: 'bug.manage' },
  warranty: {
    view: 'warranty.view',
    create: 'warranty.create',
    claim: 'warranty.claim',
  },
};

// Default permission set per system role used by the seeder.
const ROLE_DEFAULTS = {
  Admin: '*', // wildcard — assign every permission key in DB
  Manager: [
    'invoice.view', 'invoice.create', 'invoice.edit_approve', 'invoice.cancel',
    'invoice.refund', 'invoice.print', 'invoice.download',
    'product.view', 'product.create', 'product.edit', 'product.adjust_stock', 'product.view_cost',
    'supplier.view', 'supplier.create', 'supplier.edit', 'supplier.purchase_order.create', 'supplier.purchase_order.pay',
    'customer.view', 'customer.create', 'customer.edit', 'customer.collect_payment', 'customer.view_balance',
    'employee.view', 'employee.create', 'employee.edit',
    'stock.view', 'stock.adjust_approve', 'stock.adjust_direct', 'stock.count_initiate', 'stock.count_approve',
    'cash.view', 'cash.adjust',
    'bank.view', 'bank.transact',
    'return.approve', 'return.process',
    'attendance.view_own', 'attendance.view_all', 'attendance.mark_manual', 'attendance.correction_approve',
    'bills.view', 'bills.pay', 'bills.manage',
    'finance.view_dashboard', 'finance.view_pl', 'finance.view_cashflow', 'finance.view_vat',
    'report.sales', 'report.inventory', 'report.customers', 'report.suppliers', 'report.employees',
    'report.attendance', 'report.warranty', 'report.returns', 'report.bills', 'report.analytics',
    'report.export_pdf', 'report.export_csv', 'report.export_excel',
    'report.employee_performance_all',
    'analytics.view_peaks', 'analytics.view_reorder',
    'backup.view', 'backup.run_manual',
    'settings.view',
    'warranty.view', 'warranty.create', 'warranty.claim',
    'user.force_logout',
  ],
  Cashier: [
    'invoice.view', 'invoice.create', 'invoice.edit_request', 'invoice.print', 'invoice.download',
    'product.view',
    'customer.view', 'customer.create', 'customer.edit', 'customer.collect_payment', 'customer.view_balance',
    'cash.view',
    'return.request',
    'attendance.view_own', 'attendance.correction_request',
    'warranty.view', 'warranty.create',
    'report.employee_performance_own',
  ],
  Warehouse: [
    'product.view', 'product.adjust_stock',
    'supplier.view',
    'stock.view', 'stock.adjust_request', 'stock.count_initiate',
    'attendance.view_own', 'attendance.correction_request',
    'report.inventory',
    'report.employee_performance_own',
  ],
};

module.exports = { PERMISSIONS, ROLE_DEFAULTS };
